min_interval: 10
mqtt:
  host: 192.168.191.14
  port: 1883
topics:
  - name: gridmeter/sensor/powerconsumecurrent/state
    aggregates: 
    - name: sum
      interval: 60
      topic: gridmeter/sensor/powerconsumecurrent/sum_1m
    - name: avg
  - name: gridmeter/sensor/powerconsumecounter/state
    aggregates: 
    - name: max
      topic: gridmeter/sensor/powerconsumecounter/max_10s
